services:
  frontend:
    build:
      context: "./timeoff_frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./timeoff_frontend:/app
 
  backend:
    build:
      context: "./timeoff_backend"
    ports:
      - "8000:8000"
    volumes:
      - ./timeoff_backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: timeoff_db
    environment:
      - POSTGRES_DB=timeoff
      - POSTGRES_USER=timeoff
      - POSTGRES_PASSWORD=timeoff
    ports:
      - "5432:5432"
    volumes:
      - timeoff_db:/var/lib/postgresql/data

volumes:
  timeoff_db: